
[general]
	#The number of slots one loses upon death. If set to -1, they'll lose ALL earned slots.
	#Range: -1 ~ 27
	loseSlotNum = 0
	#The number of slots a player starts with.
	#Range: 9 ~ 36
	startingSlots = 18
	#Allows you to unlock slots by completing advancements.
	unlockViaAdvancements = false
	#Allows you to unlock slots using trophies.
	canUseTrophy = false
	#Allows you to buy trophies from villagers. Disabling this will disable any trophies bought from villagers!
	canBuyTrophy = false
	#Allows you to set whether or not you lose slots on death.
	loseSlots = false
	#Render settings for locked slots. 0 = Crossed out; 1 = Grayed out; 2 = Grayed and crossed out; 3 = no special rendering.
	reverseOrder = false
	#List of advancements to either white or black listed. Each advancement should be separated by a ';'. Example:"minecraft:story/smelt_iron;minecraft:story/shiny_gear"
	advancmentList = ""
	#Use a white, black, or no list of advancements to filter.
	#Allowed Values: WHITE, BLACK, NONE
	listMode = "NONE"

