
#Ultimate Unicorn Mod Configuration
[ultimate_unicorn_mod]
	#This disables notifications.
	disable_notifications = false
	#If true, Nightmares will not make fire where they walk.
	suppress_nightmare_fire = false
	#If true, fire made by Nightmares doesn't hurt or spread.
	gentle_nightmare_fire = true
	#If true, a magic horse won't suffocate when its head is in a wall. Set to true if you have this kind of problems.
	horses_cannot_suffocate = false
	#If true, Wand of Fireball items do nothing.
	disable_fire_wand = false
	#If true, Wand of Call Lightning items do nothing.
	disable_lightning_wand = false
	#If true, Wand of Dropsies items do nothing.
	disable_dropsy_wand = false
	#If true, custom horse powers cannot be used.
	disable_all_custom_horse_powers = false
	#If true, Kirin will not be able to use their breath weapon.
	suppress_kirin_fire = false
	#If true, Velvet, Mystical Healer will be unable to summon bunnies.
	suppress_bunnies = false
	#Turns off aura sparkles for unicorns.
	suppress_auras = false
	#If true, unridden destriers and other big horses can break blocks when they rear (or Typhon charges).
	unridden_horses_break_blocks = true
	#If true, unridden destriers and other big horses can break leaves (and other wimpy things) by walking into them.
	unridden_destriers_break_leaves = true
	#If true, rearing horses can hurt players and other nice creatures.
	horse_rearing_hurts_friendlies = true
	#If true, magical horses will have higher max health, like in the old days.
	use_old_horse_health_max = false
	#If true, horses will attack monsters they don't like when not ridden.
	horses_attack_monsters = true
	#If true, horses will attack zombie pigmen when not ridden.
	horses_attack_pigmen = true
	#Show Stirrups on Magical Horses.
	show_stirrups = false
	#Use alternate "fiery" skin for Typhon.
	use_typhon_alternate_skin = false
	#Max bunnies allowed in Velvet 's entourage.
	#Range: 0 ~ 100
	max_bunnies = 5
	#Max zombie minions allowed for Typhon to have summoned at once.
	#Range: 0 ~ 100
	max_zombie_minions = 5
	#Region ID
	#Range: 0 ~ 3
	region_id = 2

	#entity: unicorn
	[ultimate_unicorn_mod.unicorn]
		#Weighted value that determines how often a group of this entity will spawn in its biome compared to other creatures.
		#Range: 0 ~ 500
		unicorn_spawn_weight = 40
		#Weighted percent probability the entity type will spawn in its biome.
		#Range: 0 ~ 20
		unicorn_spawn_min_in_group = 2
		#Weighted percent probability the entity type will spawn in its biome.
		#Range: 0 ~ 20
		unicorn_spawn_max_in_group = 4

	#entity: pegasus
	[ultimate_unicorn_mod.pegasus]
		#Weighted value that determines how often a group of this entity will spawn in its biome compared to other creatures.
		#Range: 0 ~ 500
		pegasus_spawn_weight = 20
		#Weighted percent probability the entity type will spawn in its biome.
		#Range: 0 ~ 20
		pegasus_spawn_min_in_group = 1
		#Weighted percent probability the entity type will spawn in its biome.
		#Range: 0 ~ 20
		pegasus_spawn_max_in_group = 4

	#entity: destrier
	[ultimate_unicorn_mod.destrier]
		#Weighted value that determines how often a group of this entity will spawn in its biome compared to other creatures.
		#Range: 0 ~ 500
		destrier_spawn_weight = 20
		#Weighted percent probability the entity type will spawn in its biome.
		#Range: 0 ~ 20
		destrier_spawn_min_in_group = 1
		#Weighted percent probability the entity type will spawn in its biome.
		#Range: 0 ~ 20
		destrier_spawn_max_in_group = 3

	#entity: nightmare
	[ultimate_unicorn_mod.nightmare]
		#Weighted value that determines how often a group of this entity will spawn in its biome compared to other creatures.
		#Range: 0 ~ 500
		nightmare_spawn_weight = 20
		#Weighted percent probability the entity type will spawn in its biome.
		#Range: 0 ~ 20
		nightmare_spawn_min_in_group = 1
		#Weighted percent probability the entity type will spawn in its biome.
		#Range: 0 ~ 20
		nightmare_spawn_max_in_group = 3

	#entity: hippocamp
	[ultimate_unicorn_mod.hippocamp]
		#Weighted value that determines how often a group of this entity will spawn in its biome compared to other creatures.
		#Range: 0 ~ 500
		hippocamp_spawn_weight = 20
		#Weighted percent probability the entity type will spawn in its biome.
		#Range: 0 ~ 20
		hippocamp_spawn_min_in_group = 2
		#Weighted percent probability the entity type will spawn in its biome.
		#Range: 0 ~ 20
		hippocamp_spawn_max_in_group = 5

	#entity: kirin
	[ultimate_unicorn_mod.kirin]
		#Weighted value that determines how often a group of this entity will spawn in its biome compared to other creatures.
		#Range: 0 ~ 500
		kirin_spawn_weight = 8
		#Weighted percent probability the entity type will spawn in its biome.
		#Range: 0 ~ 20
		kirin_spawn_min_in_group = 1
		#Weighted percent probability the entity type will spawn in its biome.
		#Range: 0 ~ 20
		kirin_spawn_max_in_group = 2

	#entity: deer
	[ultimate_unicorn_mod.deer]
		#Weighted value that determines how often a group of this entity will spawn in its biome compared to other creatures.
		#Range: 0 ~ 500
		deer_spawn_weight = 20
		#Weighted percent probability the entity type will spawn in its biome.
		#Range: 0 ~ 20
		deer_spawn_min_in_group = 2
		#Weighted percent probability the entity type will spawn in its biome.
		#Range: 0 ~ 20
		deer_spawn_max_in_group = 5

