
#Common configuration settings
[common]
	#Check for new versions of Vampirism on startup
	versionCheck = false
	#Send mod version, MC version and mod count to mod author
	collectStats = false
	#Use the vanilla campfire block instead of Vampirism's much cooler one
	useVanillaCampfire = false
	#Whether to modify the village world gen (size and frequency), based on world config
	villageModify = true
	#INTERNAL - Set to 'never' if you don't want to be notified about integration mods
	integrationsNotifier = ""
	#INTERNAL
	optifineBloodvisionWarning = false

